// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9OgKDKOua6gFwc27nbvxoLZ34LcRSrjQ',
    appId: '1:40328375160:web:896a8defee97a9e419368d',
    messagingSenderId: '40328375160',
    projectId: 'amityfier',
    authDomain: 'amityfier.firebaseapp.com',
    storageBucket: 'amityfier.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2OAYiaMvnQCjQP_BBJtBAGCvl4dwUmj4',
    appId: '1:40328375160:android:ed8749947d9e82bf19368d',
    messagingSenderId: '40328375160',
    projectId: 'amityfier',
    storageBucket: 'amityfier.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbTSxizSEVCsyEgb-SHn0oXf2IAfmdvKk',
    appId: '1:40328375160:ios:e4c89699646bc1f119368d',
    messagingSenderId: '40328375160',
    projectId: 'amityfier',
    storageBucket: 'amityfier.appspot.com',
    iosBundleId: 'com.example.animatedLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbTSxizSEVCsyEgb-SHn0oXf2IAfmdvKk',
    appId: '1:40328375160:ios:f622a7c72f957cf819368d',
    messagingSenderId: '40328375160',
    projectId: 'amityfier',
    storageBucket: 'amityfier.appspot.com',
    iosBundleId: 'com.example.animatedLogin.RunnerTests',
  );
}
